#### 【 ndarray 객체 생성 】

In [1]:
## 모듈 로딩
import numpy as np

In [5]:
## ==============================================
## 함수 : numpy.ndarray() 
## ==============================================
## numpy ndarray객체 생성 
nparray01=np.array([1,2,3,4,5])

## ndarray 속성 
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape      =', nparray01.shape)
print('nparray01.size       =', nparray01.size)       ## 원소 개수
print('nparray01.itemsize   =', nparray01.itemsize)   ## 원소 1개 저장 바이트 수 
print('nparray01.dtype      =', nparray01.dtype)      ## 원소들의 타입
print(nparray01)


type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape      = (5,)
nparray01.size       = 5
nparray01.itemsize   = 8
nparray01.dtype      = int64
[1 2 3 4 5]


In [ ]:
## numpy ndarray객체 생성 + 데이터 타입 설정 
nparray01=np.array([1,2,3,4,5], dtype=np.float16)

## ndarray 속성 
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape      =', nparray01.shape)
print('nparray01.size       =', nparray01.size)       ## 원소 개수
print('nparray01.itemsize   =', nparray01.itemsize)   ## 원소 1개 저장 바이트 수 
print('nparray01.dtype      =', nparray01.dtype)      ## 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape      = (5,)
nparray01.size       = 5
nparray01.itemsize   = 1
nparray01.dtype      = int8
[1 2 3 4 5]


In [9]:
## numpy ndarray객체 생성 : 다른 타입의 데이터가 섞인 경우 자동 형변환
nparray01=np.array([1,2.,3,4,5])   ## 2. 실수데이터 때문에 전체를 실수로 저장

## ndarray 속성 
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape      =', nparray01.shape)
print('nparray01.size       =', nparray01.size)       ## 원소 개수
print('nparray01.itemsize   =', nparray01.itemsize)   ## 원소 1개 저장 바이트 수 
print('nparray01.dtype      =', nparray01.dtype)      ## 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape      = (5,)
nparray01.size       = 5
nparray01.itemsize   = 8
nparray01.dtype      = float64
[1. 2. 3. 4. 5.]


In [ ]:
## numpy ndarray객체 생성 : 다른 타입의 데이터가 섞인 경우 자동 형변환
nparray01=np.array([1,'2',3,4,5])                     ## '2' 때문에 전체를 유니코드로 저장

## ndarray 속성 
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape      =', nparray01.shape)
print('nparray01.size       =', nparray01.size)       ## 원소 개수
print('nparray01.itemsize   =', nparray01.itemsize)   ## 원소 1개 저장 바이트 수 
print('nparray01.dtype      =', nparray01.dtype)      ## 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape      = (5,)
nparray01.size       = 5
nparray01.itemsize   = 84
nparray01.dtype      = <U21
['1' '2' '3' '4' '5']


In [13]:
## numpy ndarray객체 생성 : 3행 2열
nparray01=np.array([[11,22], [33,44], [55,66]])                    

## ndarray 속성 
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape      =', nparray01.shape)
print('nparray01.size       =', nparray01.size)       ## 원소 개수
print('nparray01.itemsize   =', nparray01.itemsize)   ## 원소 1개 저장 바이트 수 
print('nparray01.dtype      =', nparray01.dtype)      ## 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape      = (3, 2)
nparray01.size       = 6
nparray01.itemsize   = 8
nparray01.dtype      = int64
[[11 22]
 [33 44]
 [55 66]]


In [15]:
## numpy ndarray객체 생성 : 3행 2열
nparray01=np.array([[[[7]]]])                    

## ndarray 속성 
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape      =', nparray01.shape)
print('nparray01.size       =', nparray01.size)       ## 원소 개수
print('nparray01.itemsize   =', nparray01.itemsize)   ## 원소 1개 저장 바이트 수 
print('nparray01.dtype      =', nparray01.dtype)      ## 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape      = (1, 1, 1, 1)
nparray01.size       = 1
nparray01.itemsize   = 8
nparray01.dtype      = int64
[[[[7]]]]
