In [1]:
import numpy as np


In [2]:
data = [1, 2, 3]
np.array(data)

array([1, 2, 3])

In [3]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
np.arange(1,10) * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
np.arange(2,1000,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

In [7]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [8]:
data = [0, 1, 2, 3, 4, 5]

arr = np.array(data)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(6)

array([0, 1, 2, 3, 4, 5])

In [13]:
arr = np.arange(3)
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

In [15]:
# np.arange(6).reshape(2, 4)
# 총 6개의 데이터가 저장되었는 데이터를 8개의 데이터가 필요한 행열로 저장하려고 해서 Error

In [23]:
data = [[0, 1, 2],
        [3, 4, 5]]
np.array(data)


array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
data = [1] * 20
np.array(data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
np.ones(20, dtype=int).reshape(4,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
arr =np.ones(100, dtype=int).reshape(10,10)
arr = arr * 255
arr

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [38]:
np.zeros(12, dtype=int).reshape(3,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
data = [1, 2, 3]
arr = np.ndarray(data, dtype=np.int32)

In [41]:
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [42]:
arr = np.array(['1', '2', '3'])
arr.dtype

dtype('<U1')

In [43]:
arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [ ]:
# a = np.array([255, 300, 128], dtype=np.uint8)
# print(a)
## 8비트 수는 255가지의 수만 표현 가능 -> Error

[255 128]


In [53]:
arr = np.array([1.1, 2.1, 3.1])
arr.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [55]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [56]:
arr = np.arange(9).reshape(3, 3)
arr[-1]

array([6, 7, 8])

In [57]:
arr = np.arange(9).reshape(3, 3)
arr[:,1]

array([1, 4, 7])

In [62]:
arr = np.arange(25).reshape(5, 5)

arr[3,2]

np.int64(17)

In [67]:
arr = np.arange(5)
arr[[1, 3]]

array([1, 3])

In [68]:
arr = np.arange(25).reshape(5, 5)
arr[1,1:]

array([6, 7, 8, 9])

In [70]:
arr = np.arange(25).reshape(5, 5)
arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [73]:
arr = np.arange(25).reshape(5, 5)
arr[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [79]:
arr[[0, -1]][:, [0, 3]]

array([[ 0,  3],
       [20, 23]])

In [ ]:
data = [1, 2, 3]
np.array(data) * 10

array([10, 20, 30])

In [81]:
np.array(data) ** 2

array([1, 4, 9])

In [83]:
np.sqrt(data)

array([1.        , 1.41421356, 1.73205081])

In [84]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.mean(axis = 0)

array([12., 18.])

In [85]:
score.std(axis=1)

array([5., 1.])

In [88]:
a = np.arange(   4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
a  * b

array([[ 0,  2],
       [ 6, 12]])

In [89]:
arr.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

In [94]:
arr[(arr > 3) & (arr < 7)]

array([4, 5, 6])

In [95]:
arr = np.array([-1, 2, -3, 4])
arr[arr < 0]

array([-1, -3])

In [97]:
arr[arr < 0] = 0
arr

array([0, 2, 0, 4])

In [101]:
arr = np.array([-1, 2, -3, 4])

abs(arr)

array([1, 2, 3, 4])

In [102]:
np.where(arr >= 0, arr + 10, arr - 10)

array([-11,  12, -13,  14])

In [107]:
arr = [1, 2, 3, 4, 5]
np.random.shuffle(arr)
arr

[1, 5, 2, 4, 3]

In [108]:
arr = np.array([1, 2, 3, 4, 5])
np.argmax(arr)

np.int64(4)

In [114]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [116]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

result = np.vstack((arr1, arr2))
print(result)


[[1 2]
 [3 4]]


In [118]:
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])